---
- name: Deploy Apache and Nginx using Docker Compose
  hosts: localhost
  become: true
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker Compose is installed
      apt:
        name: docker-compose
        state: present

    - name: Copy Docker Compose file for Apache
      copy:
        src: docker-compose-apache.yml
        dest: /tmp/docker-compose-apache.yml

    - name: Copy Docker Compose file for Nginx
      copy:
        src: docker-compose-nginx.yml
        dest: /tmp/docker-compose-nginx.yml

    - name: Deploy Apache container
      command: docker-compose -f /tmp/docker-compose-apache.yml up -d
      args:
        chdir: /tmp

    - name: Deploy Nginx container
      command: docker-compose -f /tmp/docker-compose-nginx.yml up -d
      args:
        chdir: /tmp

    - name: Ensure Apache is running
      docker_container:
        name: apache_server
        state: started

    - name: Ensure Nginx is running
      docker_container:
        name: nginx_server
        state: started
