---
- hosts: webservers
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update apt and install Docker
      apt:
        update_cache: yes
        name: docker-ce
        state: present

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create Docker Compose directory
      file:
        path: /opt/docker
        state: directory

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: /opt/docker/docker-compose.yml

    - name: Create directories for web content
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - /opt/docker/nginx/html
        - /opt/docker/apache/html

    - name: Create index.html for Nginx
      copy:
        content: "<html><body><h1>Welcome to Nginx</h1></body></html>"
        dest: /opt/docker/nginx/html/index.html
        mode: '0644'

    - name: Create index.html for Apache
      copy:
        content: "<html><body><h1>Welcome to Apache</h1></body></html>"
        dest: /opt/docker/apache/html/index.html
        mode: '0644'

    - name: Start Docker Compose services
      command: docker-compose up -d
      args:
        chdir: /opt/docker

