version: '3'
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    ports:
      - "8080:80"
    container_name: apache_server

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8081:80"
    container_name: nginx_server
