---
- name: Deploy Apache and Nginx using Docker Compose
  hosts: localhost
  become: true
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker Compose is installed
      apt:
        name: docker-compose
        state: present

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: /tmp/docker-compose.yml

    - name: Copy Dockerfile for Apache
      copy:
        src: Dockerfile.apache
        dest: /tmp/Dockerfile.apache

    - name: Copy Dockerfile for Nginx
      copy:
        src: Dockerfile.nginx
        dest: /tmp/Dockerfile.nginx

    - name: Copy web content
      copy:
        src: public-html/
        dest: /tmp/public-html/
        mode: "0755"

    - name: Deploy containers with Docker Compose
      command: docker-compose -f /tmp/docker-compose.yml up -d
      args:
        chdir: /tmp

    - name: Ensure Apache container is running
      docker_container:
        name: apache_server
        state: started

    - name: Ensure Nginx container is running
      docker_container:
        name: nginx_server
        state: started
